# spring.datasource.url=jdbc:mysql://localhost:3306/clinicHelperDb
# spring.datasource.username=root
# spring.datasource.password=P@ssw0rd
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
# server.port=8081
server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/clinicHelperDb
        username: root
        password: P@ssw0rd
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: 
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: MYSQL
        database-platform: